### ISSUE TITLE
inductor tail

### ISSUE THREAD

**Issue by RAMESHBABU18** [oneops/setup#24]
Hello Team,

inductor tail command giving below error
could you help as.

2016-03-21 10:36:11,168 ERROR   FailoverTransport:1099  Failed to connect to [ss
l://localhost:61617?keepAlive=true] after: 1 attempt(s)
2016-03-21 10:36:11,169 ERROR   DefaultMessageListenerContainer:929     Could no
t refresh JMS Connection for destination 'queue://shared.ind-wo' - retrying usin
g FixedBackOff{interval=5000, currentAttempts=105, maxAttempts=unlimited}. Cause
: Connection refused

**Comment by RAMESHBABU18** [comment]
2016-03-17 19:04:11,436	 INFO	ClassPathXmlApplicationContext:510	Refreshing org.springframework.context.support.ClassPathXmlApplicationContext@51521cc1: startup date [Thu Mar 17 19:04:11 UTC 2016]; root of context hierarchy
2016-03-17 19:04:11,559	 INFO	XmlBeanDefinitionReader:317	Loading XML bean definitions from class path resource [application-context.xml]
2016-03-17 19:04:17,219	 INFO	DefaultListableBeanFactory:822	Overriding bean definition for bean 'config': replacing [Generic bean: class [com.oneops.inductor.Config]; scope=singleton; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=null; destroyMethodName=null; defined in URL [jar:file:/usr/local/share/gems/gems/oneops-admin-1.0.0/target/inductor-1.1.0.jar!/com/oneops/inductor/Config.class]] with [Generic bean: class [com.oneops.inductor.Config]; scope=; abstract=false; lazyInit=false; autowireMode=0; dependencyCheck=0; autowireCandidate=true; primary=false; factoryBeanName=null; factoryMethodName=null; initMethodName=init; destroyMethodName=null; defined in class path resource [application-context.xml]]
2016-03-17 19:04:17,731	 INFO	PropertyPlaceholderConfigurer:172	Loading properties file from class path resource [inductor.properties]
2016-03-17 19:04:17,731	 INFO	PropertyPlaceholderConfigurer:172	Loading properties file from URL [file:/opt/oneops/inductor/clouds-enabled/shared/conf/inductor.properties]
2016-03-17 19:04:31,412	 INFO	Config:348	Inductor IP : 10.0.2.15 (enp0s3)
2016-03-17 19:04:31,412	 INFO	Config:301	using dns config: /opt/oneops/inductor/global/dns.conf
2016-03-17 19:04:31,412	 INFO	Config:318	not a public inductor - missing: /opt/oneops/inductor/global/dns.conf
2016-03-17 19:04:31,836	 INFO	CachingConnectionFactory:311	Established shared JMS Connection: ActiveMQConnection {id=ID:localhost.localdomain-34989-1458241471728-1:1,clientId=null,started=false}
2016-03-17 19:04:44,572	ERROR	FailoverTransport:1099	Failed to connect to [ssl://localhost:61617?keepAlive=true] after: 1 attempt(s)
2016-03-17 19:04:44,574	ERROR	MessagePublisher:67	Connection refused
2016-03-17 19:04:44,574	ERROR	MessagePublisher:68	Connection refused
javax.jms.JMSException: Connection refused
	at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:72)
	at org.apache.activemq.ActiveMQConnection.syncSendPacket(ActiveMQConnection.java:1434)
	at org.apache.activemq.ActiveMQConnection.ensureConnectionInfoSent(ActiveMQConnection.java:1521)
	at org.apache.activemq.ActiveMQConnection.createSession(ActiveMQConnection.java:329)
	at org.springframework.jms.connection.SingleConnectionFactory.createSession(SingleConnectionFactory.java:437)
	at org.springframework.jms.connection.CachingConnectionFactory.getSession(CachingConnectionFactory.java:234)
	at org.springframework.jms.connection.SingleConnectionFactory$SharedConnectionInvocationHandler.invoke(SingleConnectionFactory.java:604)
	at com.sun.proxy.$Proxy11.createSession(Unknown Source)
	at com.oneops.inductor.MessagePublisher.init(MessagePublisher.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1694)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1633)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1562)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:194)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:755)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:139)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:83)
	at com.oneops.inductor.Listener.main(Listener.java:391)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at org.apache.activemq.transport.tcp.TcpTransport.connect(TcpTransport.java:501)
	at org.apache.activemq.transport.tcp.TcpTransport.doStart(TcpTransport.java:464)
	at org.apache.activemq.util.ServiceSupport.start(ServiceSupport.java:55)
	at org.apache.activemq.transport.AbstractInactivityMonitor.start(AbstractInactivityMonitor.java:138)
	at org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:58)
	at org.apache.activemq.transport.WireFormatNegotiator.start(WireFormatNegotiator.java:72)
	at org.apache.activemq.transport.failover.FailoverTransport.doReconnect(FailoverTransport.java:1027)
	at org.apache.activemq.transport.failover.FailoverTransport$2.iterate(FailoverTransport.java:149)
	at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:133)
	at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2016-03-17 19:04:44,578	 WARN	CachingConnectionFactory:322	Encountered a JMSException - resetting the underlying JMS Connection
javax.jms.JMSException: Connection refused
	at org.apache.activemq.util.JMSExceptionSupport.create(JMSExceptionSupport.java:54)
	at org.apache.activemq.ActiveMQConnection.onAsyncException(ActiveMQConnection.java:1997)
	at org.apache.activemq.ActiveMQConnection.onException(ActiveMQConnection.java:2016)
	at org.apache.activemq.transport.TransportFilter.onException(TransportFilter.java:101)
	at org.apache.activemq.transport.ResponseCorrelator.onException(ResponseCorrelator.java:126)
	at org.apache.activemq.transport.TransportFilter.onException(TransportFilter.java:101)
	at org.apache.activemq.transport.failover.FailoverTransport.propagateFailureToExceptionListener(FailoverTransport.java:1166)
	at org.apache.activemq.transport.failover.FailoverTransport.doReconnect(FailoverTransport.java:1113)
	at org.apache.activemq.transport.failover.FailoverTransport$2.iterate(FailoverTransport.java:149)
	at org.apache.activemq.thread.PooledTaskRunner.runTask(PooledTaskRunner.java:133)
	at org.apache.activemq.thread.PooledTaskRunner$1.run(PooledTaskRunner.java:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
	at org.apache.activemq.transport.tcp.TcpTransport.connect(TcpTransport.java:501)
	at org.apache.activemq.transport.tcp.TcpTransport.doStart(TcpTransport.java:464)
	at org.apache.activemq.util.ServiceSupport.start(ServiceSupport.java:55)
	at org.apache.activemq.transport.AbstractInactivityMonitor.start(AbstractInactivityMonitor.java:138)
	at org.apache.activemq.transport.TransportFilter.start(TransportFilter.java:58)
	at org.apache.activemq.transport.WireFormatNegotiator.start(WireFormatNegotiator.java:72)
	at org.apache.activemq.transport.failover.FailoverTransport.doReconnect(FailoverTransport.java:1027)
	... 6 more

**Comment by nimkar** [comment]
Can you provide some more details on your installation ? Is this a vagrant installation ?

**Comment by RAMESHBABU18** [comment]
ya, we are using vagrant installation.
we running Next step vagrant start  command we got below message.
" **[ooadmin@localhost inductor]$ inductor start
       start  already running
       start  shared logstash_agent already running** "
after that we run 
vagrant tail command
This command giving above error

**Comment by schwankl** [comment]
looks like your activemq broker was down.  Did you figure it out?   Closing ; please reopen if still an issue
