### ISSUE TITLE
/home/oneops/dist files not found

### ISSUE THREAD

**Issue by RAMESHBABU18** [oneops/setup#30]
==> default: tar: Error is not recoverable: exiting now
==> default: /home/oneops/init_db.sh: line 8: cd: /home/oneops/dist/cms-db-pkg: No such file or directory
==> default: tar (child): db.tar.gz: Cannot open: No such file or directory
==> default: tar (child): Error is not recoverable: exiting now
==> default: tar: Child returned status 2
==> default: tar: Error is not recoverable: exiting now
==> default: cp: cannot stat ‘/home/oneops/dist/cms-db-pkg/db/single_db_schemas.sql’: No such file or directory
==> default: /var/lib/pgsql/single_db_schemas.sql: No such file or directory
==> default: /home/oneops/init_db.sh: line 15: cd: /home/oneops/dist/cms-db-pkg/db: No such file or directory
==> default: /home/oneops/init_db.sh: line 16: ./single_db_install.sh: No such file or directory
==> default: Completed DB init : 09:40:24
==> default: Deploying artifacts: 09:40:24
==> default: tar (child): oneops-continuous.tar.gz: Cannot open: No such file or directory
==> default: tar (child): Error is not recoverable: exiting now
==> default: Deploying Display component: 09:40:24
==> default: tar: Child returned status 2
==> default: tar: Error is not recoverable: exiting now
==> default: mv: cannot stat ‘/home/oneops/dist/oneops/dist/app.tar.gz’: No such file or directory
==> default: tar (child): app.tar.gz: Cannot open: No such file or directory
==> default: tar (child): Error is not recoverable: exiting now
==> default: tar: Child returned status 2
==> default: tar: Error is not recoverable: exiting now
==> default: Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
==> default: installing your bundle as root will break this application for all non-root
==> default: users on this machine.
==> default: Could not locate Gemfile or .bundle/ directory
==> default: rake aborted!
==> default: No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
==> default:

**Comment by vkchalam** [comment]
Root cause of most of the issues:
The VM is provisioned via 2 shell scripts 
oo-prereqs.sh and oo-setup.sh
oo-setup.sh installs jenkins on the vm and configures a bunch of jobs that need to run. These jobs in-turn, checkout code from github related to all the components that need to be built in order for the oneops installation to work.
These jenkins jobs are failing.
All of the jobs fail with:


`FATAL: null
java.lang.NullPointerException
    at org.jenkinsci.plugins.buildnamesetter.BuildNameSetter.setUp(BuildNameSetter.java:41)
    at hudson.model.Build$BuildExecution.doRun(Build.java:156)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
    at hudson.model.Run.execute(Run.java:1738)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
Archiving artifacts
[Boolean condition] checking [false] against [^(1|y|yes|t|true|on|run)$] (origin token: ${ENV,var="TAG"})
Run condition [Boolean condition] preventing perform for step [[Git Publisher]]`

That error relates to NOT being able to set a build's name

![image](https://cloud.githubusercontent.com/assets/7029136/14908775/6e43b946-0d90-11e6-92d3-1654a9a5f9a1.png)

The GIT_REVISION variable resolves to null, thereby causing all builds to break, there by leaving us with an incomplete installation.

Fixes to the above issues:
Go to http://localhost:3003
Manually Configure each build there to just uncheck Set Build Name 
Alternatively you could SSH into the vm and go to /home/oneops/build/build-wf/jobs and use a sed command to remove the following text from all of the jobs' config.xml file
`<buildWrappers>
    <org.jenkinsci.plugins.buildnamesetter.BuildNameSetter plugin="build-name-setter@1.3">
      <template>${GIT_REVISION,length=8}</template>
    </org.jenkinsci.plugins.buildnamesetter.BuildNameSetter>
  </buildWrappers>`
 
vagrant ssh
cd /home/oneops/build/build-wf/jobs
sudo find ./* -name "config.xml" -exec sed -i '/<buildWrappers>/,/<\/buildWrappers>/d' {} \;
 
 
Then edit your Vagrantfile to comment this line
#config.vm.provision :shell, path: "oo-prereqs.sh"
Then run vagrant provision  (this is so that only oo-setup.sh runs again on the VM)
This time you should have a complete installation

**Comment by ighouri** [comment]
@vkchalam Isnt ${GIT_REVISON) a variable available in your Jenkin's server and supposed to GIT sha id ? What is the Jenkin server version you get by the way ? Do you have a token-macro plugin installed in /home/oneops/build/build-wf/plugins ?

**Comment by kvolety-nisum-com** [comment]
@ighouri GIT_REVISION would be an environment variable set by some plugin that get's installed with jenkins. Per the Rakefile https://github.com/oneops/build-wf/blob/master/Rakefile , the jenkins server is version 1.642.1.  Also all the plugins listed here: https://github.com/oneops/build-wf/blob/master/plugins.txt will get installed and most of the plugins don't specify a version. This will cause the latest version of the plugins to get installed.

I suspect one of the GIT related plugins (maybe version x)  might have been setting the GIT_REVISION environment variable...and since the latest plugins get installed when some one tries a fresh setup...the new version of the plugin does not set GIT_REVISION but sets something else instead...causing GIT_REVISION to resolve to null
